version: '3.8'

services:
  flask-app:
    container_name: flask-app
    image: younggyolee/vfs-flask
    ports:
      - "5001:5001"

  springboot-app:
    container_name: springboot-app
    image: younggyolee/vfs-springboot
    ports:
      - "8080:8080"
    depends_on:
      - flask-app