version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-py
    container_name: flask-app
    ports:
      - "5001:5001"

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - flask-app