spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env.local[.properties]
  jpa:
    hibernate:
      ddl-auto: create

ffmpeg:
  location: /opt/homebrew/Cellar/ffmpeg/7.0_1/bin/ffmpeg
ffprobe:
  location: /opt/homebrew/Cellar/ffmpeg/7.0_1/bin/ffprobe

---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
  paths-to-match:
    - /**
  cache:
    disabled: true