name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot Application with Gradle
        run: ./gradlew bootJar

      - name: Build Flask Docker Image
        run: |
          docker build -t younggyolee/vfs-flask -f Dockerfile-py .

      - name: Build Spring Boot Docker Image
        run: |
          docker build -t younggyolee/vfs-springboot -f Dockerfile .

      - name: Push Flask Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push younggyolee/vfs-flask

      - name: Push Spring Boot Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push younggyolee/vfs-springboot

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/

            sudo touch .env.dev
            echo "${{ secrets.ENV_VARS }}" | sudo tee .env.dev > /dev/null

            sudo touch docker-compose.yml
            echo "${{ vars.DOCKER_COMPOSE }}" | sudo tee docker-compose.yml > /dev/null

            sudo chmod 666 /var/run/docker.sock
            sudo docker rm -f $(docker ps -qa)

            sudo docker pull younggyolee/vfs-flask
            sudo docker pull younggyolee/vfs-springboot

            docker-compose -f docker-compose.yml --env-file ./.env.dev up -d
            docker image prune -f